### ISSUE TITLE
The Links to phpwcms Wiki from your README.md give an Error 403 (Forbidden) back.

### ISSUE THREAD

**Issue by uwe367** [jensensen/NLU_FF_AC_QD#1]
The Links to phpwcms Wiki from your README.md give an Error 403 (Forbidden) back.
Can you correct this please?

**Comment by jensensen** [comment]
Any idea, what happend with the .phpwcms-howto?

**Comment by jensensen** [comment]
Ahh, you can now find it on https://wiki.phpwcms.org/
Thank you!

**Comment by uwe367** [comment]
Thanks for the correction.
